Set-StrictMode -Version 3


[string]$BASEDIR = Resolve-Path (Join-Path $PSScriptRoot '..' '..')

$VALID_DB = 'pgsql', 'mysql', 'mssql', 'oracle', 'mariadb'
$VALID_PHP_VERSION = '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0'
$VALID_APP_RUNTIME = 'ionic3', 'ionic5'
$VALID_HOST_PORT = '(?<HOST>\d+\.\d+\.\d+\.\d+:)?(?<PORT>[1-9]\d*)'
$VALID_BROWSER = '^(?<NAME>chrome|firefox)(:(?<TAG>.+))?$'

$Defaults = @{
    COMPOSE_PROJECT_NAME                    = 'moodle-docker'
    MOODLE_DOCKER_WWWROOT                   = $null
    MOODLE_DOCKER_WEB_HOST                  = 'localhost'
    MOODLE_DOCKER_WEB_PORT                  = $null
    MOODLE_DOCKER_PHP_VERSION               = '7.4'
    MOODLE_DOCKER_BEHAT_FAILDUMP            = $null

    MOODLE_DOCKER_DB                        = 'pgsql'

    MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES = $null

    MOODLE_DOCKER_SELENIUM_VNC_PORT         = $null
    MOODLE_DOCKER_BROWSER                   = 'firefox:3'

    MOODLE_DOCKER_APP_PATH                  = $null
    MOODLE_DOCKER_APP_VERSION               = $null
    MOODLE_DOCKER_APP_RUNTIME               = $null
}

function MOODLE_DOCKER_WWWROOT($Value) {
}


function
$ParamaterDef = @{
    COMPOSE_PROJECT_NAME                    = @{
        Default = 'moodle-docker'
        Validation = {
        }
    }
    MOODLE_DOCKER_WWWROOT                   = @{
        Default = null
    }
    MOODLE_DOCKER_WEB_HOST                  = @{
        Default = 'localhost'
    }
    MOODLE_DOCKER_WEB_PORT                  = @{
        Default = $null
    }
    MOODLE_DOCKER_PHP_VERSION               = @{
        Default = '7.4'
    }
    MOODLE_DOCKER_BEHAT_FAILDUMP            = @{
        Default = $null
    }
    MOODLE_DOCKER_DB                        = @{
        Default = 'pgsql'
    }
    MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES = @{
        Default = $null
    }
    MOODLE_DOCKER_SELENIUM_VNC_PORT         = @{
        Default = $null
    }
    MOODLE_DOCKER_BROWSER                   = @{
        Default = 'firefox:3'
    }
    MOODLE_DOCKER_APP_PATH                  = @{
        Default = $null
    }
    MOODLE_DOCKER_APP_VERSION               = @{
        Default = $null
    }
    MOODLE_DOCKER_APP_RUNTIME               = @{
        Default = $null
    }
}

<#
    .SYNOPSIS
    Convert all path seperators to unix (/)
    #>
filter NormalizePath {
    $_.ToString() -replace '(/|\\)+', '/'
}

<#
    .SYNOPSIS
    Execute an external command.

    .DESCRIPTION
    Execute an external command (passed as a string) and determine its
    sucess or failure. On failure throw a terminating error. Otherwise
    return the output generated by the command.

    .EXAMPLE
    Invoke-Exec 'docker build .'

    .EXAMPLE
    Invoke-Exec 'docker-compose.exe' 'exec webserver php vendor/bin/behat' -Verbose

    Write output to the Verbose stream as it occurs, Useful for example when watching a
    long running process.

    .NOTES
    1. The external command is executed in a seperate process to ensure environment isolation.
    2. Standard Error outputs are captured rather than flowing through to the console
    3. If the -Verbose option is used, or $VerbosePreference is set to 'Continue', output
    is echoed to the console as it occurs.

#>
function Invoke-Exec {
    [CmdletBinding()]
    param (
        # The external command (executable or script) to be executed.
        # Can be the name of an executable in the $Path or the full or relative
        # path to an executable file.
        [Parameter(Mandatory, Position = 0)]
        [string]
        [ValidateNotNullOrEmpty()]
        $Command,

        # The arguments to be passed to the command.
        [Parameter(Position = 1)]
        [string]
        [ValidateNotNullOrEmpty()]
        $CommandArgs = '',

        # Environment variables to be set prior to executing the command. These are
        # set in the context of the process.
        [Parameter()]
        [hashtable]
        $EnvVars = @{}
    )

    $proc = [System.Diagnostics.Process]::New()

    $proc.StartInfo.UseShellExecute = $false
    $proc.StartInfo.RedirectStandardError = $true
    $proc.StartInfo.RedirectStandardOutput = $true
    $proc.StartInfo.CreateNoWindow = $true
    $proc.StartInfo.FileName = $Command
    $proc.StartInfo.Arguments = $CommandArgs

    # Set environment variables
    foreach ($var in $EnvVars.GetEnumerator()) {
        $proc.StartInfo.EnvironmentVariables.Add($var.Name, $var.Value)
    }

    [void]$proc.Start()

    # Setup async reads to avoid deadlocks
    # Loop on ReadLineAsync so we can show output to the user if Verbose is set
    $out = while ($line = $proc.StandardOutput.ReadLineAsync().GetAwaiter().GetResult()) {
        # If Verbose is set, emit output to the Berbose stream
        Write-Verbose $Line

        # Collect output
        # [void]$out.Add($line)
        $line
    }

    # Read all error output asynchronously
    $errtask = $proc.StandardError.ReadToEndAsync()

    $proc.WaitForExit()

    # Get the error results
    $err = $errtask.GetAwaiter().GetResult()

    if ($proc.ExitCode) {
        throw $err
    }

    $out
}

class Stack {
    [hashtable]$Params
    [hashtable]$Environment
    [hashtable]$Defaults
    [System.Collections.ArrayList]$ComposeFiles = @()

    [string]$ComposeExe
    [string[]]$ComposeCommandArgs
    [string[]]$ComposeFilePaths = @(
        $PWD
        $BASEDIR
    )

    Stack([hashtable]$Environment, [string[]]$ComposeFiles) {
        $this.Environment = $Environment
        $this.ComposeFiles = $ComposeFiles
        $this.SetupDocker()
    }

    Stack([hashtable]$Params) {
        $ErrorActionPreference = 'Stop'
        $this.Params = $Params.Clone()
        $this.Environment = @{
            BASEDIR                       = $script:BASEDIR
            ASSETDIR                      = (Join-Path $script:BASEDIR 'assets')
            COMPOSE_CONVERT_WINDOWS_PATHS = 'true'
            COMPOSE_PATH_SEPERATOR        = ';'
        }
        $this.ComposeFiles = [System.Collections.ArrayList]::New()
        $this.SetupDocker()
        $this.SetEnvironment()
        $this.ValidateEnvironment()
        $this.SetComposeFiles()
    }

    [void] SetupDocker() {
        if ($this.GetDockerComposeVersion() -ge [version]'2.0') {
            $this.ComposeExe = 'docker'
            $this.ComposeCommandArgs = @('compose')
        }
        else {
            $this.ComposeExe = 'docker-compose'
            $this.ComposeCommandArgs = @()
        }
    }

    [hashtable] GetParams([hashtable]$PassedParams) {
        $StackParams = $script:Defaults.Clone()
        foreach ($name in $PassedParams.Keys) {
            if (-Not $StackParams.ContainsKey()) {
                throw "Unrecognized Parameter $name"
            }
        }
        foreach ($Name in $StackParams.Keys) {
            $envpath = "Env:$Name"
            $StackParams[$name] = switch ($Name) {
                { $PassedParams.ContainsKey($Name) } { [string]($PassedParams[$name]); break }
                { Test-Path $envpath } { (Get-Item $envpath).Value; break }
            }
        }
    }

    # Set environment first from passed parameters, then then $Env then default
    [void] SetEnvironment() {
        foreach ($Name in $script:Defaults.Keys) {
            $envpath = "Env:$Name"
            $this.Environment.$Name = switch ($Name) {
                { $this.Params.ContainsKey($Name) } { [string]($this.Params.$name); break }
                { Test-Path $envpath } { (Get-Item $envpath).Value; break }
                default { $script:Defaults.$Name }
            }
        }
    }

    [string] EnvOrDefault([string]$Name, [string]$Default) {
        if ($this.Environment.ContainsKey($Name)) {
            return [string]$this.Environment.$name
        }
        else {
            return $default
        }
    }

    # Validate, normalize and derive environment values
    [void] ValidateEnvironment() {
        # webserver
        $this.AssertDirExists('MOODLE_DOCKER_WWWROOT')
        $this.AssertInSet('MOODLE_DOCKER_PHP_VERSION', $script:VALID_PHP_VERSION)
        $this.NormalizeHostPort('MOODLE_DOCKER_WEB_PORT')

        # db
        $db = $this.EnvOrDefault('MOODLE_DOCKER_DB', $null)
        if ($db) {
            $this.AssertInSet('MOODLE_DOCKER_DB', $script:VALID_DB)
        }
        else {
            $this.Environment.MOODLE_DOCKER_DB = 'pgsql'
        }

        # selenium
        $this.NormalizeHostPort('MOODLE_DOCKER_SELENIUM_VNC_PORT')
        $this.AssertMatch('MOODLE_DOCKER_BROWSER', $script:VALID_BROWSER)
        $this.Environment.MOODLE_DOCKER_BROWSER_NAME = $this.GetBrowserName()
        $this.Environment.MOODLE_DOCKER_BROWSER_TAG = $this.GetBrowserTag()

        # moodleapp
        if ($this.Environment.MOODLE_DOCKER_APP_PATH -and $this.Environment.MOODLE_DOCKER_APP_VERSION) {
            throw 'Cannot specify both MOODLE_DOCKERAPP_PATH and MOODLE_DOCKER_APP_VERSION'
        }
        if ($this.Environment.MOODLE_DOCKER_APP_PATH) {
            $this.AssertDirExists('MOODLE_DOCKER_APP_PATH')
        }
        if ($Value = $this.Environment.MOODLE_DOCKER_APP_VERSION) {
            try { [version]$Value }
            catch { throw "'MOODLE_DOCKER_APP_VERSION' ($Value) is not a valid version" }
        }
        $this.Environment.MOODLE_DOCKER_APP_RUNTIME = $this.GetAppRuntime()
    }

    # [string[]] SetComposeFiles([hashtable]$Environment) {

    #     $Files = @(
    #         @{
    #             FileName  = 'base.yml'
    #             Condition = { $true }
    #         }
    #         @{
    #             FileName  = 'service.mail.yml'
    #             Condition = { $true }
    #         }
    #         @{
    #             FileName  = "db.$($Environment.MOODLE_DOCKER_DB).yml"
    #             Condition = { $Environment.MOODLE_DOCKER_DB -ne 'pgsql' }
    #         }
    #         @{
    #             FileName  = "db.$($Environment.MOODLE_DOCKER_DB).$($Environment.MOODLE_DOCKER_PHP_VERSION).yml"
    #             Condition = { $ComposeFile -and (Test-Path $ComposeFile -PathType Leaf) }
    #         }
    #         @{
    #             FileName  = "selenium.$($Environment.MOODLE_DOCKER_BROWSER_NAME).yml"
    #             Condition = { $Environment.MOODLE_DOCKER_BROWSER_NAME -ne 'firefox' }
    #         }
    #         @{
    #             FileName  = 'selenium.debug.yml'
    #             Condition = { $Environment.MOODLE_DOCKER_SELENIUM_VNC_PORT }
    #         }
    #         @{
    #             FileName  = "moodle-app-dev-$($Environment.MOODLE_DOCKER_APP_RUNTIME).yml"
    #             Condition = { $Environment.MOODLE_DOCKER_APP_PATH }
    #         }
    #         @{
    #             FileName  = "moodle-app-$($Environment.MOODLE_DOCKER_APP_RUNTIME).yml"
    #             Condition = { $Environment.MOODLE_DOCKER_APP_VERSION }
    #         }
    #         @{
    #             FileName  = 'phpunit-external-services.yml'
    #             Condition = { $Environment.MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES }
    #         }
    #         @{
    #             FileName  = 'webserver.port.yml'
    #             Condition = { $Environment.MOODLE_DOCKER_WEB_PORT }
    #         }
    #         @{
    #             FileName  = 'volumes-cached.yml'
    #             Condition = { $global:IsMacOs }
    #         }

    #         foreach ($File in $Rules) {

    #         }
    #     )
    # }

    # @{
    #     File      = $this.Environment.MOODLE_DOCKER_BROWSER_NAME -ne 'firefox'
    #     Condition = { "selenium.$($this.Environment.MOODLE_DOCKER_BROWSER_NAME).yml" }
    # }
    [void] SetComposeFiles() {
        $this.AddComposeFile(
            'base.yml',
            { $true }
        )
        $this.AddComposeFile('service.mail.yml', { $true } )
        $this.AddComposeFile(
            "db.$($this.Environment.MOODLE_DOCKER_DB).yml",
            { $this.Environment.MOODLE_DOCKER_DB -ne 'pgsql' }
        )
        $this.AddComposeFile(
            "db.$($this.Environment.MOODLE_DOCKER_DB).$($this.Environment.MOODLE_DOCKER_PHP_VERSION).yml",
            { $ComposeFile -and (Test-Path $ComposeFile -PathType Leaf) }
        )
        $this.AddComposeFile(
            "selenium.$($this.Environment.MOODLE_DOCKER_BROWSER_NAME).yml",
            { $this.Environment.MOODLE_DOCKER_BROWSER_NAME -ne 'firefox' })
        $this.AddComposeFile(
            'selenium.debug.yml',
            { $this.Environment.MOODLE_DOCKER_SELENIUM_VNC_PORT }
        )
        $this.AddComposeFile(
            "moodle-app-dev-$($this.Environment.MOODLE_DOCKER_APP_RUNTIME).yml",
            { $this.Environment.MOODLE_DOCKER_APP_PATH }
        )
        $this.AddComposeFile(
            "moodle-app-$($this.Environment.MOODLE_DOCKER_APP_RUNTIME).yml",
            { $this.Environment.MOODLE_DOCKER_APP_VERSION }
        )
        $this.AddComposeFile(
            'phpunit-external-services.yml',
            { $this.Environment.MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES }
        )
        $this.AddComposeFile(
            'webserver.port.yml',
            { $this.Environment.MOODLE_DOCKER_WEB_PORT }
        )
        $this.AddComposeFile(
            'volumes-cached.yml',
            { $global:IsMacOs }
        )
    }

    [boolean] IncludesApp() {
        return ($this.Environment.MOODLE_DOCKER_APP_PATH -or $this.Environment.MOODLE_DOCKER_APP_VERSION)
    }

    [string] GetAppRuntime() {
        # If neither app path nor app version are specified, return $null
        if (-Not $this.Environment.MOODLE_DOCKER_APP_PATH -or $this.Environment.MOODLE_DOCKER_APP_VERSION) {
            return $null
        }

        # If $Value is set verify it is a valid runtime and return it
        if ($this.Environment.MOODLE_DOCKER_APP_RUNTIME) {
            $this.AssertInSet('MOODLE_DOCKER_APP_RUNTIME', $this.Environment.MOODLE_DOCKER_APP_RUNTIME, $script:VALID_APP_RUNTIME)
            return $this.Environment.MOODLE_DOCKER_APP_RUNTIME
        }

        # Infer runtime from version
        $AppVersion = $this.GetAppVersion()
        if (-Not $AppVersion) {
            throw 'Unable to determine AppVersion'
        }

        if ($appversion -ge [version]'3.9.5') { return 'ionic5' } else { return 'ionic3' }
    }

    [version] GetDockerComposeVersion() {
        $verstring = $null
        try {
            $Invocation = @{
                Command     = 'docker'
                CommandArgs = 'compose version'
            }
            $verstring = Invoke-Exec @Invocation
        }
        catch {
            $Invocation = @{
                Command     = 'docker-compose'
                CommandArgs = 'version'
            }
            $verstring = Invoke-Exec @Invocation
        }
        if ($verstring -match '^.* v(?<VERSION>.+)$') {
            return [version]$Matches.VERSION
        }
        else {
            throw "Unable to parse docker compose version from $verstring"
        }
    }

    [version] GetAppVersion() {
        if ($this.Environment.MOODLE_DOCKER_APP_VERSION) {
            return $this.Environment.MOODLE_DOCKER_APP_VERSION
        }
        elseif ($this.Environment.MOODLE_DOCKER_APP_PATH) {
            $pkgfile = Join-Path $this.Environment.MOODLE_DOCKER_APP_PATH 'package.json'
            $package = Get-Content $pkgfile | ConvertFrom-Json -Depth 5 -ErrorAction Stop
            if (-Not $package.ContainsKey('version') -or (-Not $package.version)) {
                throw "$pkgfile does not specify version"
            }
            return $package.version
        }
        else {
            return $null
        }
    }

    [void] NormalizeHostPort([string]$ParameterName) {
        $value = $this.EnvOrDefault($ParameterName, $null)
        $valid = $value -match $script:VALID_HOST_PORT
        if (-Not $value) {
            $this.Environment[$ParameterName] = $null #ensure value
        }
        elseif (-Not $valid) {
            throw "$ParameterName ($_) must be a port number greater than 0 or string in the form <HOST>:<port>"
        }
        elseif (-Not $Matches.ContainsKey('HOST')) {
            $this.Environment[$ParameterName] = "127.0.0.1:$($value)"
        }
        # else no changes
    }

    [string] GetBrowserName() {
        $null = $this.Environment.MOODLE_DOCKER_BROWSER -match $script:VALID_BROWSER
        return $Matches.NAME
    }

    [string] GetBrowserTag() {
        $null = $this.Environment.MOODLE_DOCKER_BROWSER -match $script:VALID_BROWSER
        $Value = switch ($Matches) {
            { $_.ContainsKey('TAG') } { $_.TAG; break }
            { $_.NAME -eq 'firefox' } { '3'; break }
            { $_.NAME -eq 'chrome' } { '3'; break }
            default {
                throw "Unsupported Browser $($_.NAME)"
            }
        }
        return $Value
    }

    [void] IncludeComposeFile([string]$FileName, [scriptblock]$Condition) {

        # Search for a file with the given name in ComposeFilePaths
        $ComposeFile = $this.ComposeFilePaths | `
                Join-Path -ChildPath $FileName | `
                Where-Object { Test-Path $_ -PathType Leaf } | `
                Select-Object -First 1

        # If file should be included
        if (& $Condition ) {
            if (-Not $ComposeFile) {
                throw "$FileName not found"
            }
            else {
                $this.ComposeFiles.Add($ComposeFile)
            }
        }
    }

    [void] AddComposeFile([string]$FileName, [scriptblock]$Condition) {

        # Find the file
        $ComposeFile = $this.ComposeFilePaths | `
                Join-Path -ChildPath $FileName | `
                Where-Object { Test-Path $_ -PathType Leaf } | `
                Select-Object -First 1

        $Include = & $Condition
        if ($Include) {
            if (-Not $ComposeFile) {
                throw "$FileName not found"
            }
            else {
                $this.ComposeFiles.Add($ComposeFile)
            }
        }
    }

    #region ASSERTIONS

    [void] AssertDirExists([string]$Name) {
        $Value = $this.Environment.$Name
        if (-Not $Value -or -Not (Test-Path $Value -PathType Container)) {
            throw "$Name references non-existing directory ($Value)"
        }
    }

    [void] AssertInSet([string]$Name, [string[]]$Set) {
        $Value = $this.Environment.$Name
        if (-Not ($Set -contains $Value)) {
            throw "$Name ($Value) must be one of $($Set -join ', ')"
        }
    }

    [void] AssertMatch([string]$Name, [string]$Regex) {
        $Value = $this.Environment.$Name
        if ($Value -notmatch $Regex) {
            throw "$Name ($value) must match $Regex"
        }
    }

    #endRegion ASSERTIONS

    [void] start() {
        $this.Invoke('up -d')
        $this.WaitDb()
        $this.WaitApp()
        Write-Verbose 'Stack started'
    }

    [Object] Invoke($Command) {
        $Invocation = $this.GetInvocation($Command)
        $result = Invoke-Exec @Invocation
        return $result
    }

    [hashtable] GetInvocation([string]$Command) {
        $files = ($this.ComposeFiles | ForEach-Object { "-f $_" }) -join ' '
        return @{
            Command     = $this.ComposeExe
            CommandArgs = "$($this.ComposeCommandArgs) $files $Command"
            EnvVars     = $this.Environment
        }
    }

    [void] WaitDb() {
        $DBType = $this.Environment.MOODLE_DOCKER_DB

        if (!$DBType) {
            throw 'MOODLE_DOCKER_DB is not set'
        }

        if ($DBType -eq 'mssql') {
            $this.Invoke('exec db /wait-for-mssql-to-come-up.sh')
        }
        elseif ($DBType -eq 'oracle') {
            while (-Not ($this.Invoke('logs db') | Select-String -Pattern 'listening on IP')) {
                Write-Verbose 'Waiting for oracle to come up...'
                Start-Sleep -Seconds 15
            }
        }
        else {
            Start-Sleep 5
        }
    }

    [void] WaitApp() {
        if ($this.IncludesApp()) {
            while (-Not ($this.Invoke('logs moodleapp') | Select-String -Pattern 'dev server running: |Angular Live Development Server is listening|Configuration complete; ready for start up')) {
                Write-Verbose 'Waiting for Moodle app to come up...'
                Start-Sleep -Seconds 15
            }
        }
    }

}

<#
    .SYNOPSIS
    Create a new Stack instance.
#>
function New-Stack {
    param(
        [Parameter(Mandatory)]
        [hashtable]$StackParams
    )

    [Stack]::New($StackParams)
}

function Get-Stack {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)]
        [System.IO.FileInfo]
        [ValidateScript(
            {
                if (-Not (Test-Path $_ -PathType Leaf)) {
                    Throw "File $_ does not exist"
                }
                $true
            }
        )]
        $Path
    )

    if (-Not $Path) {
        # Look for stack.json or stack.env if current directory or any parent
        $loc = Get-Location
        while ($loc -and !$result) {
            foreach ($target in 'stack.json', 'stack.env') {
                $f = Join-Path $loc $target
                if (Test-Path $f -PathType Leaf) {
                    $Path = $f
                }
            }
            if (!$Path) {
                # Now look in parent dir
                $loc = Split-Path $loc -Parent
            }
        }
    }

    if ($Path) {
        if ($Path.Name -eq 'stack.json') {
            # Import previously exported stack definition
            Import-Stack $Path
        }
        elseif ($Path.Name -eq 'stack.env') {
            # Parse parameters from the file
            $data = Import-Csv $Path -Delimiter '=' -Header Name, Value
            $params = @{}
            foreach ($item in $data) {
                $params[$item.Name] = $item.Value
            }
            New-Stack @params
        }
    }
    else {
        # New-Stack will attempt to set parameters from environment variables and default values
        New-Stack -ErrorAction Stop
    }
}

function Start-Stack {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromPipeline)]
        [Stack]$Stack
    )

    Process {
        if (-Not $Stack) {
            $Stack = Get-Stack -ErrorAction Stop
        }
        $Stack.Start() | Invoke-Stack 'up -d'
    }
}

function Invoke-Stack {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromPipeline)]
        [Stack]$Stack,

        [Parameter(Position = 0)]
        [string]$Command
    )

    Process {
        if (-Not $Stack) {
            $Stack = Get-Stack -ErrorAction Stop
        }
        $Stack.Invoke($Command)
    }
}

function Import-Stack {
    [CmdletBinding()]
    param(
        [string]$Path
    )

    if (-Not $Path) {
        $FileName = 'stack.json'
        $loc = Get-Location
        while (-Not $Path -and $loc) {
            $filepath = Join-Path $loc $FileName
            if (Test-Path $filepath -PatyType Container) {
                $Path = $filepath
            }
            else {
                $loc = Split-Path $loc -Parent
            }
        }
        if (-Not $Path) {
            throw 'Unable to find stack.json in current directory or any parent'
        }
    }

    $props = Get-Content $Path | ConvertFrom-Json

}

function Export-Stack {
    [CmdletBinding()]
    param(
        [string]$Path = (Join-Path $PWD 'stack.json')
    )

    $Hash = @{
        Environment  = $Stack.Environment
        ComposeFiles = $Stack.ComposeFiles
    }

    $Hash | ConvertTo-Json | Out-File -FilePath $Path -Force

}

$exports = @{
    Variable = '*'
    Function = @(
        'New-Stack'
        'Get-Stack'
        'Start-Stack'
        'Invoke-Stack'
    )
}

Export-ModuleMember @exports